name: Republish

on:
  schedule:
    - cron: '1 18 * * *'  # Run at 6:01 pm every day
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger GitHub Pages rebuild
        run: |
          curl -i \
            --request POST \
            --url https://api.github.com/repos/hanaEdonnelly/DirtyPower/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN" \
            --header "Accept: application/vnd.github+json"
  env:
    USER_TOKEN: ${{ secrets.USER_TOKEN }}
