name: Republish

on:
  schedule:
    - cron: '1 18 * * *'
  workflow_dispatch:

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GitHub Pages rebuild
        env:
          USER_TOKEN: ${{ secrets.USER_TOKEN }}
        run: |
          curl -i \
            --request POST \
            --url https://api.github.com/repos/hanaEdonnelly/DirtyPower/pages/builds \
            --header "Authorization: Bearer $USER_TOKEN" \
            --header "Accept: application/vnd.github+json"